In [1]:
import sys
import time

import gym
import gym_novel_gridworlds
import numpy as np

# %matplotlib inline
# %matplotlib nbagg

# pip install PyQt5
%matplotlib qt

In [2]:
env_id = 'NovelGridworld-v0'

env = gym.make(env_id)
print("action_space:", env.action_space)
print("observation_space:", env.observation_space)
print("observation_space.low:", env.observation_space.low)
print("observation_space.high:", env.observation_space.high)
print("sample:", env.observation_space.sample(), env.action_space.sample())

action_space: Discrete(3)
observation_space: Box(10,)
observation_space.low: [1 1 1 1 1 1 1 1 1 1]
observation_space.high: [11 11 11 11 11 11 11 11 11 11]
sample: [ 5  5  7  8  4  5 10  1  5  6] 1


# Random Actions

In [ ]:
obs = env.reset()
for i in range(50):
    action = env.action_space.sample()  # take a random action
    print("action: ", action, env.action_str[action])
    # print("agent_location: ", env.agent_location)
    observation, reward, done, info = env.step(action)
    env.render()
    print("Step: " + str(i) + ", reward: ", reward)
    print("observation: ", observation)
    time.sleep(0)

#     if (i+1) % 10 == 0:
#         env.map_size = np.random.randint(low=10, high=20, size=1)[0]
#         obs = env.reset()
#         print("")

env.close()

action:  0 Forward
Step: 0, reward:  -1
observation:  [11  6 11  8  4 11 11  4 11  3]
action:  0 Forward
Step: 1, reward:  -1
observation:  [11  6 11  7  3 11 11  4 11  3]
action:  1 Left
Step: 2, reward:  -1
observation:  [ 3 11 11  4 11  3 11  4 11  4]
action:  1 Left
Step: 3, reward:  -1
observation:  [11  3 11  4 11  4 11  5 11  6]
action:  0 Forward
Step: 4, reward:  -1
observation:  [11  3 11  4 11  3 11  4 11  6]
action:  1 Left
Step: 5, reward:  -1
observation:  [11  3 11  4 11  6 11  8  4 11]
action:  0 Forward
Step: 6, reward:  -1
observation:  [11  3 11  4 11  5 11  7 11  6]
action:  0 Forward
Step: 7, reward:  -1
observation:  [11  3 11  4 11  4 11  5 11  6]
action:  1 Left
Step: 8, reward:  -1
observation:  [11  4 11  5 11  6 11  7 11  5]
action:  2 Right
Step: 9, reward:  -1
observation:  [11  3 11  4 11  4 11  5 11  6]
action:  0 Forward
Step: 10, reward:  -1
observation:  [11  3 11  4 11  3 11  4 11  6]
action:  2 Right
Step: 11, reward:  -1
observation:  [11  6 11  4 1

# Train DQN

In [3]:
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines.deepq.policies import MlpPolicy
from stable_baselines import DQN

from stable_baselines.bench import Monitor

log_dir = 'experiments'
env = Monitor(env, log_dir)

model = DQN(MlpPolicy, env, verbose=1, prioritized_replay=True)
#model = DQN(MlpPolicy, env, verbose=1, double_q=False, tensorboard_log="./sb_dqn_tensorboard/")
# model = DQN(MlpPolicy, env, verbose=1, tensorboard_log="./stable_baselines_DQN_tensorboard/", prioritized_replay=True)

model.learn(total_timesteps=100000) # not work: 10000, works: 100000
model.save("deepq_"+env_id)
#model.save("deepq_"+env_id+"_new2")

#del model # remove to demonstrate saving and loading

c:\anaconda3\envs\py3_7_sb\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\anaconda3\envs\py3_7_sb\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\anaconda3\envs\py3_7_sb\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\anaconda3\envs\py3_7_sb\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarnin







Instructions for updating:
Use keras.layers.flatten instead.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


model.q_values:  Tensor("deepq/model/add:0", shape=(?, 3), dtype=float32)
step_model.q_values:  Tensor("deepq/step_model/model/add:0", shape=(?, 3), dtype=float32)
double_policy.q_values:  Tensor("deepq/double_q/model/add:0", shape=(?, 3), dtype=float32)
target_policy.q_values:  Tensor("deepq/target_q_func/model/add:0", shape=(?, 3), dtype=float32)

q_func_vars:  [<tf.Variable 'deepq/model/action_value/fully_connected/weights:0' shape=(10, 64) dtype=float32_ref>, <tf.Variable 'deepq/model/action_value/fully_connected/biases:0' shape=(64,) dtype=float32_ref>, <tf.Variable 'deepq/model/action_value/fully_connected_1/weights:0' shape=(64, 64) dtype=float32_ref>, <tf.Variable 'deepq/model/action_value/fully_connected_1/biases:0' shape=(64,) dtype=float32_ref>, <tf.Variable 'deepq/model/action_value/fully_connected_2/weights:0' shape=(64, 3) dtype=float32_ref>, <tf.Variable 'deepq/model/action_value/fully_connected_2/biases:0' shape=(3,) dtype=float32_ref>, <tf.Variable 'deepq/model/state_v

--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 500      |
| mean 100 episode reward | 39.1     |
| steps                   | 12727    |
--------------------------------------
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 600      |
| mean 100 episode reward | 41.8     |
| steps                   | 13651    |
--------------------------------------
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 700      |
| mean 100 episode reward | 44.4     |
| steps                   | 14311    |
--------------------------------------
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 800      |
| mean 100 episode reward | 44.6     |
| steps                   | 14947    |
--------------------------------------
--------------------------------------
| % time spent exploring 

--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 4100     |
| mean 100 episode reward | 42.7     |
| steps                   | 41259    |
--------------------------------------
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 4200     |
| mean 100 episode reward | 43.5     |
| steps                   | 42014    |
--------------------------------------
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 4300     |
| mean 100 episode reward | 42.3     |
| steps                   | 42884    |
--------------------------------------
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 4400     |
| mean 100 episode reward | 43.5     |
| steps                   | 43632    |
--------------------------------------
--------------------------------------
| % time spent exploring 

--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 7700     |
| mean 100 episode reward | 42.3     |
| steps                   | 74390    |
--------------------------------------
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 7800     |
| mean 100 episode reward | 41.7     |
| steps                   | 75318    |
--------------------------------------
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 7900     |
| mean 100 episode reward | 41.2     |
| steps                   | 76298    |
--------------------------------------
--------------------------------------
| % time spent exploring  | 2        |
| episodes                | 8000     |
| mean 100 episode reward | 43.5     |
| steps                   | 77051    |
--------------------------------------
--------------------------------------
| % time spent exploring 

In [4]:
model = DQN.load("deepq_"+env_id)
# model = DQN.load("deepq_"+env_id+"_new2")

for i_episode in range(10):
    print("EPISODE STARTS")
    obs = env.reset()
    for i in range(100):
        action, _states = model.predict(obs)
        obs, reward, done, info = env.step(action)
        env.render()
        print("Episode #: " + str(i_episode) + ", step: " + str(i) + ", reward: ", reward)
        # End the episode if agent is dead
        if done:
            print("Episode #: "+str(i_episode)+" finished after "+str(i)+" timesteps\n")
            time.sleep(1)
            break

Loading a model without an environment, this model cannot be trained until it has a valid environment.


model.q_values:  Tensor("deepq/model/add:0", shape=(?, 3), dtype=float32)
step_model.q_values:  Tensor("deepq/step_model/model/add:0", shape=(?, 3), dtype=float32)
double_policy.q_values:  Tensor("deepq/double_q/model/add:0", shape=(?, 3), dtype=float32)
target_policy.q_values:  Tensor("deepq/target_q_func/model/add:0", shape=(?, 3), dtype=float32)
q_func_vars:  [<tf.Variable 'deepq/model/action_value/fully_connected/weights:0' shape=(10, 64) dtype=float32_ref>, <tf.Variable 'deepq/model/action_value/fully_connected/biases:0' shape=(64,) dtype=float32_ref>, <tf.Variable 'deepq/model/action_value/fully_connected_1/weights:0' shape=(64, 64) dtype=float32_ref>, <tf.Variable 'deepq/model/action_value/fully_connected_1/biases:0' shape=(64,) dtype=float32_ref>, <tf.Variable 'deepq/model/action_value/fully_connected_2/weights:0' shape=(64, 3) dtype=float32_ref>, <tf.Variable 'deepq/model/action_value/fully_connected_2/biases:0' shape=(3,) dtype=float32_ref>, <tf.Variable 'deepq/model/state_va

EPISODE STARTS
Episode #: 9, step: 0, reward:  -1
Episode #: 9, step: 1, reward:  -1
Episode #: 9, step: 2, reward:  -1
Episode #: 9, step: 3, reward:  -1
Episode #: 9, step: 4, reward:  -1
Episode #: 9, step: 5, reward:  -1
Episode #: 9, step: 6, reward:  50
Episode #: 9 finished after 6 timesteps



# Decoding DQN

In [4]:
from stable_baselines.deepq.policies import MlpPolicy
help(MlpPolicy)

Help on class MlpPolicy in module stable_baselines.deepq.policies:

class MlpPolicy(FeedForwardPolicy)
 |  MlpPolicy(sess, ob_space, ac_space, n_env, n_steps, n_batch, reuse=False, obs_phs=None, dueling=True, **_kwargs)
 |  
 |  Policy object that implements DQN policy, using a MLP (2 layers of 64)
 |  
 |  :param sess: (TensorFlow session) The current TensorFlow session
 |  :param ob_space: (Gym Space) The observation space of the environment
 |  :param ac_space: (Gym Space) The action space of the environment
 |  :param n_env: (int) The number of environments to run
 |  :param n_steps: (int) The number of steps to run for each environment
 |  :param n_batch: (int) The number of batch to run (n_envs * n_steps)
 |  :param reuse: (bool) If the policy is reusable or not
 |  :param obs_phs: (TensorFlow Tensor, TensorFlow Tensor) a tuple containing an override for observation placeholder
 |      and the processed observation placeholder respectively
 |  :param dueling: (bool) if true doubl

In [4]:
from stable_baselines import DQN
help(DQN)

c:\anaconda3\envs\py3_7_sb\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\anaconda3\envs\py3_7_sb\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\anaconda3\envs\py3_7_sb\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\anaconda3\envs\py3_7_sb\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarnin

Help on class DQN in module stable_baselines.deepq.dqn:

class DQN(stable_baselines.common.base_class.OffPolicyRLModel)
 |  DQN(policy, env, gamma=0.99, learning_rate=0.0005, buffer_size=50000, exploration_fraction=0.1, exploration_final_eps=0.02, exploration_initial_eps=1.0, train_freq=1, batch_size=32, double_q=True, learning_starts=1000, target_network_update_freq=500, prioritized_replay=False, prioritized_replay_alpha=0.6, prioritized_replay_beta0=0.4, prioritized_replay_beta_iters=None, prioritized_replay_eps=1e-06, param_noise=False, n_cpu_tf_sess=None, verbose=0, tensorboard_log=None, _init_setup_model=True, policy_kwargs=None, full_tensorboard_log=False, seed=None)
 |  
 |  The DQN model class.
 |  DQN paper: https://arxiv.org/abs/1312.5602
 |  Dueling DQN: https://arxiv.org/abs/1511.06581
 |  Double-Q Learning: https://arxiv.org/abs/1509.06461
 |  Prioritized Experience Replay: https://arxiv.org/abs/1511.05952
 |  
 |  :param policy: (DQNPolicy or str) The policy model to use 

# Summary of SB's DQN

DQN Tricks:
- Dueling DQN
- Double-Q Learning
- Prioritized Experience Replay

There are 4 networks:
- model: It's behavior/Q-network, used for learning/optimization
- step_model: It's input is same as model (obs_phs), and its also used for for learning/optimization. But, its also used when we have to take action in the env.
- double_q: its a separate network like target_network used to compute td_errors
- target_network: periodically Q-network is copied to target_network

model.q_values:  Tensor("deepq/model/add:0", shape=(?, 3), dtype=float32)
step_model.q_values:  Tensor("deepq/step_model/model/add:0", shape=(?, 3), dtype=float32)
double_policy.q_values:  Tensor("deepq/double_q/model/add:0", shape=(?, 3), dtype=float32)
target_policy.q_values:  Tensor("deepq/target_q_func/model/add:0", shape=(?, 3), dtype=float32)

Implementation Details:
- A network is created by MlpPolicy, which has "model" scope
    - model is used to optimize
- This model is copied to 3 models under different scopes: step_model, double_q, target_q_func
    - step_model is uded to take actions or predict function
    - target_q_func is computed the error
- Input (obs_phs=obs_phs) is connected to model and step_model 
- Initially output of all network is same:
```
num_timesteps:  0
[[-0.41003048 -0.33983934  3.8062277 ]] - model q_values
[[-0.41003048 -0.33983934  3.8062277 ]] - step_model q_values
[[-0.41003048 -0.33983934  3.8062277 ]] - double_policy q_values
[[-0.41003048 -0.33983934  3.8062277 ]] - target_policy q_values
```
- When training starts model, step_model, double_q is updated:
```
num_timesteps:  1001
[[2.5672882 2.647919  6.15353  ]] - model q_values
[[2.5672882 2.647919  6.15353  ]] - step_model q_values
[[2.5672882 2.647919  6.15353  ]] - double_policy q_values
[[1.8600085 2.0999918 6.044751 ]] - target_policy q_values
```
- For training, experience data is sampled using priorities based on td_errors
- After every 500 steps, model parameters is copied to target_policy, so their output becomes same:
```
num_timesteps:  1500
[[-0.13262868  0.72109544  0.81133664]] - model q_values
[[-0.13262868  0.72109544  0.81133664]] - step_model q_values
[[-0.13262868  0.72109544  0.81133664]] - double_policy q_values
[[-0.13262868  0.72109544  0.81133664]] - target_policy q_values
```
